name: Build and Test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
  release:
    types: [created]

jobs:
  ramani:
    name: Build and test ramani
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        working-directory: ./ramani
        run: |
            ./gradlew build
            ./gradlew test
      - name: Publish (Maven)
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        working-directory: ./ramani
        run: |
            echo -n "${{ secrets.MAVEN_SIGNING_KEY }}" | base64 --decode | gpg --import
            ./gradlew -PossrhUsername=${{ secrets.OSSRH_USERNAME }} -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} publish

  annotation-simple:
    name: "Build and test example: AnnotationSimple"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use ramani as composite build
        working-directory: ./examples/annotation-simple
        run: echo "includeBuild '../../ramani'" >> settings.gradle
      - name: Build
        working-directory: ./examples/annotation-simple
        run: |
            ./gradlew build
            ./gradlew test

  interactive-polygon:
    name: "Build and test example: InteractivePolygon"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use ramani as composite build
        working-directory: ./examples/interactive-polygon
        run: echo "includeBuild '../../ramani'" >> settings.gradle
      - name: Build
        working-directory: ./examples/interactive-polygon
        run: |
            ./gradlew build
            ./gradlew test

