name: Build and Test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
  release:
    types: [created]

jobs:
  ramani:
    name: Build and test ramani
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get patched annotation plugin
        run: git clone https://github.com/ramani-maps/maplibre-plugins-android
      - name: Setup composite build
        run: echo "includeBuild '../maplibre-plugins-android/plugin-annotation'" >> ramani/settings.gradle
      - name: Build
        working-directory: ./ramani
        run: |
            ./gradlew build
            ./gradlew test

